services:
  # Five Rivers Tutoring - Production Environment (Custom Docker Image)
  fiverivers-wp:
    image: fiverivertutoring-wordpress:latest
    container_name: fiverivers-wp-prod
    restart: always
    ports:
      - "8081:80"
    environment:
      # External Database Configuration
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      
      # WordPress Site Configuration
      WORDPRESS_HOME: ${WORDPRESS_HOME}
      WORDPRESS_SITEURL: ${WORDPRESS_SITEURL}
      WORDPRESS_DEBUG: 0
      WP_ENVIRONMENT_TYPE: production
    volumes:
      # Persistent storage for uploads and cache
      - fiverivers_uploads:/var/www/html/wp-content/uploads
      - fiverivers_cache:/var/www/html/wp-content/cache
      # NO wp-content mount (uses image content)
    networks:
      - fiverivers_network
    # No depends_on - external database connection

volumes:
  fiverivers_uploads:
  fiverivers_cache:

networks:
  fiverivers_network:
    driver: bridge 