services:
  # Five Rivers Tutoring - Staging Environment (Custom Docker Image)
  fiverivers-wp:
    image: fiverivertutoring-wordpress:staging
    container_name: fiverivers-wp-staging
    restart: always
    env_file:
      - fiverivertutoring-wordpress-staging.properties
    ports:
      - "8083:80"
    volumes:
      # Images are now part of the Docker image
      - fiverivers_cache:/var/www/html/wp-content/cache
      # NO wp-content mount (uses image content)
    networks:
      - fiverivers_network
    # No depends_on - external database connection

volumes:
  fiverivers_cache:

networks:
  fiverivers_network:
    driver: bridge 