services:
  # Five Rivers Tutoring - Production Environment (Custom Docker Image)
  fiverivers-wp:
    image: fiverivertutoring-wordpress:latest
    container_name: fiverivers-wp-prod
    restart: always
    env_file:
      - properties/fiverivertutoring-wordpress.properties
    ports:
      - "80:80"
    volumes:
      # Persistent storage for uploads and cache
      - fiverivers_uploads:/var/www/html/wp-content/uploads
      - fiverivers_cache:/var/www/html/wp-content/cache
    networks:
      - fiverivers_network

volumes:
  fiverivers_uploads:
  fiverivers_cache:

networks:
  fiverivers_network:
    driver: bridge


